version: "3.7"
services:
  database:
    image: postgres
    container_name: database
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_USER=pgres
      - POSTGRES_PASSWORD=L0l2345234
      - POSTGRES_DB=test_db
    env_file:
      - .env
    ports:
      - "5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: